### PR TITLE
add message placeholder substitution

### PR DESCRIPTION
**Pull request by piksel**
Hello! This is my own addition to fblog that I use to highlight variables in logs. This makes it much easier to see the relevant data when sifting through lots of almost identical log messages.

Example:
[asciicast](https://asciinema.org/a/584648)

It was originally modeled to work with JSON representations of [PSR-3 logs](https://www.php-fig.org/psr/psr-3/), hence the `{placeholder}` and `context` being the default values, but it should be dynamic enough to work with several common interpolation formats.

If this something that you would like to include, I can make some adjustments to  make it fit better (and write som tests :)).

### CODE REVIEW

**Comment by bomgar** [comment]
Looks nice. I didn't have time to look at the code yet.

Could you extend the sample json files with some context lines?

**Comment by piksel** [comment]
Added a context sample file and fixed the clippy warnings.

**Comment by bomgar** [comment]
Looks really nice. The only thing missing is a few tests for the message template and some example in the README. Maybe it is about time the to replace the existing screenshot there.

**Comment by piksel** [comment]
Added some usage info to the README. I haven't used org mode in a loong time though, but I think it should render correctly.
Also, I added a svg for the example output to make it a bit clearer.

The sample log would look like this using the same method ([ansisvg](https://github.com/wader/ansisvg)):

sample_context

**Comment by bomgar** [comment]
The feature is always on now. It seems `ArgPredicate::IsPresent` is not working.

**Comment by piksel** [comment]
> The feature is always on now. It seems `ArgPredicate::IsPresent` is not working.

The docs have bug/typo 🙄:
https://docs.rs/clap/latest/clap/builder/struct.Arg.html#examples-45

The first example they add a `default_value_if`, but then they supply the flag in the test, which means that it would work regardless. This was what I used to implement it, but if we look at the **next** example, they actually have replaced `ArgPredicate::IsPresent` with `"true"` (because otherwise the example would not pass the assert).
I will open a issue in clap about this.

**Comment by bomgar** [comment]
Thank you. Now I have to find reasons to use this in my log files :smile:

**Pull request merged**
